version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keyclock
      - mssql
  keyclock:
    image: "quay.io/keycloak/keycloak:21.0.1"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - start-dev --features=token-exchange
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: "sql-1"
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "123456789Qwerty"
      ACCEPT_EULA: "Y"