version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keyclock
  keyclock:
    image: "quay.io/keycloak/keycloak:21.0.1"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - start-dev --features=token-exchange