version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keyclock
      - mongo
  keyclock:
    image: "bitnami/keycloak"
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789Qwerty