version: "3.9"
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
  keyclock:
    image: "bitnami/keycloak"
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
